"""RQ1 visualization: compare 4 baselines on Accuracy / High-confidence Coverage.

Methods compared:
    1. AgentPerms (IC+CF)        -- reuses existing ../results/ic_cf_predictions.json
    2. No Personalization        -- ../results/no_personalization_predictions.json
    3. Clustering Personalization-- ../results/clustering_personalization_predictions.json
    4. Federated MoE             -- ../results/federated_moe_predictions.json
    5. MoE-only (centralized)    -- ../results/moe_rq1_predictions.json

For each method we sweep a confidence threshold tau in [0.50, 0.95] and report:
    - Accuracy on samples with confidence >= tau
    - Coverage (fraction of samples that pass the threshold)

Outputs:
    ../results/rq1_accuracy_vs_threshold.png
    ../results/rq1_coverage_vs_threshold.png
    ../results/rq1_threshold_curves.json

Run AFTER all 3 trainable baselines have finished (IC+CF was generated by
the original paper code -- see permission_ic_cf.py).
"""

import json
import os

import numpy as np

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except ImportError as exc:
    raise ImportError(
        "matplotlib is required for rq1_visualization.py.\n"
        "Install with: pip install matplotlib"
    ) from exc


RESULTS_DIR = "../results"

ACCURACY_FIG = os.path.join(RESULTS_DIR, "rq1_accuracy_vs_threshold.png")
COVERAGE_FIG = os.path.join(RESULTS_DIR, "rq1_coverage_vs_threshold.png")
CURVES_JSON = os.path.join(RESULTS_DIR, "rq1_threshold_curves.json")

# Confidence thresholds (LLM scores + max(p, 1-p) both live in [0.5, 1.0])
THRESHOLDS = np.round(np.arange(0.50, 0.96, 0.05), 2)


METHODS = [
    {
        "name": "AgentPerms (IC+CF)",
        "loader": "ic_cf",
        "path": os.path.join(RESULTS_DIR, "ic_cf_predictions.json"),
        "color": "#7f7f7f",
        "marker": "o",
        "linestyle": "--",
    },
    {
        "name": "No Personalization",
        "loader": "simple",
        "path": os.path.join(RESULTS_DIR, "no_personalization_predictions.json"),
        "color": "#1f77b4",
        "marker": "s",
        "linestyle": "-",
    },
    {
        "name": "Clustering",
        "loader": "simple",
        "path": os.path.join(RESULTS_DIR, "clustering_personalization_predictions.json"),
        "color": "#2ca02c",
        "marker": "^",
        "linestyle": "-",
    },
    {
        "name": "Federated MoE",
        "loader": "simple",
        "path": os.path.join(RESULTS_DIR, "federated_moe_predictions.json"),
        "color": "#d62728",
        "marker": "D",
        "linestyle": "-",
    },
    {
        "name": "MoE-only",
        "loader": "simple",
        "path": os.path.join(RESULTS_DIR, "moe_rq1_predictions.json"),
        "color": "#9467bd",
        "marker": "P",
        "linestyle": "-.",
    },
]


def load_simple_predictions(path):
    """Load our standardized RQ1 prediction format.

    Each record has y_true, p_allow, pred, confidence. We recompute confidence
    here as max(p_allow, 1 - p_allow) for consistency (in case some files
    store it differently).
    """
    with open(path, "r", encoding="utf-8") as f:
        preds = json.load(f)
    y_true = np.array([p["y_true"] for p in preds], dtype=int)
    p_allow = np.array([p["p_allow"] for p in preds], dtype=float)
    pred = (p_allow >= 0.5).astype(int)
    confidence = np.maximum(p_allow, 1.0 - p_allow)
    return y_true, pred, confidence


def load_ic_cf_predictions(path):
    """Load AgentPerms IC+CF predictions.

    The LLM emits {label, score} per (data_type) -- "score" is its confidence
    in the chosen label, already in [0,1] (and typically clustered close to
    1). We use it directly as our confidence value, matching the paper's
    evaluation logic in permission_ic_cf.py.
    """
    with open(path, "r", encoding="utf-8") as f:
        results = json.load(f)

    y_true_list, y_pred_list, conf_list = [], [], []

    for _, data in results.items():
        if data.get("skipped") or "error" in data:
            continue

        predictions = data.get("predictions", [])
        ground_truth = data.get("ground_truth", [])
        gt_by_qid = {g["id"]: g.get("answer", {}) for g in ground_truth}

        for pred_item in predictions:
            qid = pred_item.get("id")
            if qid is None or qid not in gt_by_qid:
                continue
            gt_perms = gt_by_qid[qid]
            pred_perms = pred_item.get("permission", {})
            for dt, pred_data in pred_perms.items():
                if dt not in gt_perms:
                    continue
                gt_label = gt_perms[dt]
                gt_b = 1 if "Yes" in gt_label else 0

                label = pred_data.get("label", "")
                raw_score = pred_data.get("score", 0.5)
                try:
                    score = float(raw_score)
                except (TypeError, ValueError):
                    score = 0.5
                score = max(0.0, min(1.0, score))
                pred_b = 1 if "Yes" in label else 0

                y_true_list.append(gt_b)
                y_pred_list.append(pred_b)
                conf_list.append(score)

    return (
        np.array(y_true_list, dtype=int),
        np.array(y_pred_list, dtype=int),
        np.array(conf_list, dtype=float),
    )


def threshold_curve(y_true, y_pred, confidence, thresholds):
    accs, covs = [], []
    for tau in thresholds:
        mask = confidence >= tau
        cov = float(mask.mean()) if len(mask) > 0 else 0.0
        if mask.sum() > 0:
            acc = float((y_pred[mask] == y_true[mask]).mean())
        else:
            acc = float("nan")
        accs.append(acc)
        covs.append(cov)
    return accs, covs


def main():
    print("=" * 60)
    print("RQ1 Visualization: 4 baselines, Accuracy + Coverage curves")
    print("=" * 60)

    curves = {}
    for method in METHODS:
        if not os.path.exists(method["path"]):
            print(f"  [skip]    {method['name']:<22}  missing: {method['path']}")
            continue
        if method["loader"] == "ic_cf":
            y_true, y_pred, conf = load_ic_cf_predictions(method["path"])
        else:
            y_true, y_pred, conf = load_simple_predictions(method["path"])

        if len(y_true) == 0:
            print(f"  [empty]   {method['name']:<22}  no predictions")
            continue

        accs, covs = threshold_curve(y_true, y_pred, conf, THRESHOLDS)
        overall_acc = float((y_pred == y_true).mean())
        curves[method["name"]] = {
            "thresholds": [float(t) for t in THRESHOLDS],
            "accuracy": accs,
            "coverage": covs,
            "n_samples": int(len(y_true)),
            "overall_accuracy": overall_acc,
        }
        print(
            f"  [loaded]  {method['name']:<22}  n={len(y_true):>4d}  "
            f"acc(@0.5)={accs[0]:.3f}  cov(@0.5)={covs[0]:.3f}  "
            f"acc(@0.8)={accs[6]:.3f}  cov(@0.8)={covs[6]:.3f}"
        )

    if not curves:
        raise RuntimeError(
            "No prediction files found. Run the baselines first:\n"
            "  python permission_no_personalization.py\n"
            "  python permission_clustering.py\n"
            "  python permission_federated_moe.py\n"
            "  python permission_moe.py\n"
            "(IC+CF is generated by the original permission_ic_cf.py.)"
        )

    os.makedirs(RESULTS_DIR, exist_ok=True)
    with open(CURVES_JSON, "w", encoding="utf-8") as f:
        json.dump(curves, f, indent=2)
    print(f"\nSaved curves -> {CURVES_JSON}")

    # ---- Accuracy plot ----
    fig, ax = plt.subplots(figsize=(7, 5))
    for method in METHODS:
        if method["name"] not in curves:
            continue
        c = curves[method["name"]]
        ax.plot(
            c["thresholds"],
            c["accuracy"],
            marker=method["marker"],
            linestyle=method["linestyle"],
            color=method["color"],
            label=method["name"],
            linewidth=1.8,
            markersize=6,
        )
    ax.set_xlabel("Confidence threshold $\\tau$")
    ax.set_ylabel("Accuracy on covered samples")
    ax.set_title("RQ1: Accuracy vs. Confidence threshold")
    ax.set_ylim(0.5, 1.02)
    ax.set_xlim(0.48, 0.97)
    ax.grid(alpha=0.3)
    ax.legend(loc="lower right", framealpha=0.9)
    fig.tight_layout()
    fig.savefig(ACCURACY_FIG, dpi=300)
    plt.close(fig)
    print(f"Saved accuracy plot -> {ACCURACY_FIG}")

    # ---- Coverage plot ----
    fig, ax = plt.subplots(figsize=(7, 5))
    for method in METHODS:
        if method["name"] not in curves:
            continue
        c = curves[method["name"]]
        ax.plot(
            c["thresholds"],
            c["coverage"],
            marker=method["marker"],
            linestyle=method["linestyle"],
            color=method["color"],
            label=method["name"],
            linewidth=1.8,
            markersize=6,
        )
    ax.set_xlabel("Confidence threshold $\\tau$")
    ax.set_ylabel("High-confidence coverage")
    ax.set_title("RQ1: High-confidence coverage vs. Confidence threshold")
    ax.set_ylim(0.0, 1.02)
    ax.set_xlim(0.48, 0.97)
    ax.grid(alpha=0.3)
    ax.legend(loc="lower left", framealpha=0.9)
    fig.tight_layout()
    fig.savefig(COVERAGE_FIG, dpi=300)
    plt.close(fig)
    print(f"Saved coverage plot -> {COVERAGE_FIG}")


if __name__ == "__main__":
    main()
